### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by sofer** [NataliaLKB/learn-git-basics#10]
I love this.

Here are some minor comments:
1. _"students of Founders & Coders 8 week coding Academy."_

perhaps change to _"students of courses at Founders & Coders"_, just because I suspect we will want to use this for our weekend courses, too.
1. `git branch new-branch`

To a novice, it may not be clear whether new-branch is a command or the name of something. `my-new-branch` might be more obvious.
1. Might be worth noting the difference between:

`git clone https://github.com/NataliaLKB/learn-git-basics.git`

and:

`git@github.com:NataliaLKB/learn-git-basics.git`

which beginners could usefully be made aware of.
1. Might be worth nothing the difference between `git push`, `git push origin` and `git push origin master`. See http://stackoverflow.com/questions/12462481/what-is-the-difference-between-git-push-origin-and-git-push-origin-master and https://www.kernel.org/pub/software/scm/git/docs/git-push.html#_examples
2. Under _"Merging Changes with Master"_ at the end, you may want to say something about comparing across forks, and about base fork and head fork otherwise there is a danger that you will get loads of pull requests into your original repo.

**Comment by NataliaLKB** [comment]
@sofer thanks for this! Great feedback.

**Comment by NataliaLKB** [comment]
@sofer  #26 answers the first part of your feedback. 

Regarding `git@github.com:NataliaLKB/learn-git-basics.git` I would like to cover this, ssh keys, and forks in a FAC section. see #20.

Lastly, regarding the differences between the `git push *` commands. I don't think this is crucial for beginners to know. I think it could work in a further resources section #24

**Comment by NataliaLKB** [comment]
Closing a I think I dealt with most of this already
