### ISSUE TITLE
What to do if a pull request cannot be automatically merged.

### ISSUE THREAD

**Issue by sofer** [NataliaLKB/learn-git-basics#11]
_"We can’t automatically merge this pull request. Use the command line to resolve conflicts before continuing."_

It might be worth briefly covering what to do if a pull request doesn't quite come off and the reasons why it might happen.

**Comment by nelsonic** [comment]
There are quite a few meme images for this section.
![got-git-conflict](http://www.quickmeme.com/img/c4/c4f1ad3cf4b18f014d46326564ebf83dff4c25a42d2e258e1c1a5be3bf8caae6.jpg)

![woody-buzz-git-merge-conflict](http://www.mememaker.net/static/images/memes/3629643.jpg)
( Pictures make it fun... :stuck_out_tongue_winking_eye: )

**Comment by NataliaLKB** [comment]
Closing as I dont have time for this now, but feel free to make an addition!
