### ISSUE TITLE
Introductions

### ISSUE THREAD

**Issue by iteles** [NataliaLKB/learn-git-basics#12]
- [ ] The [repeated introduction](https://github.com/NataliaLKB/learn-git-basics/blame/1116839e12c4165cb1b232747b466189e216ec7c/README.md#L39) is unnecessary for the introduction section. You could use this space to give a two line overview of what version control is and how it's used in 'plain English', or leave it out altogether.
- [ ] For Git Collaboration, you _do_ need an introduction section as it's much later in the tutorial - what you have is good but it's not actually an introduction to the section, it would be nice to see a two sentence overview of what this section is about and covers

**Comment by NataliaLKB** [comment]
Thats helpful! I will remove the repeated intro in both sections. 

Regarding version control. I would prefer the definitions remain mostly in the terminology section. Unless you think it is necessary?

**Comment by iteles** [comment]
No, that sounds totally fine, it was just in case you wanted an additional introduction below your contents :)

**Comment by iteles** [comment]
:warning: I updated the issue (so as not to open another on the topic of introductions) and added a checkbox in the [original comment](https://github.com/NataliaLKB/learn-git-basics/issues/12#issue-66856574) with notes for the Git Collaboration part of your tutorial.

**Comment by NataliaLKB** [comment]
Closing for now. But if anyone wants to pick this up feel free!
