### ISSUE TITLE
Minor suggestions for Git for Collaboration

### ISSUE THREAD

**Issue by sofer** [NataliaLKB/learn-git-basics#13]
Could replace:

```
touch time/newfile.txt
open time/newfile.txt
```

With:

```
date > time/newfile.txt
```

or

```
echo "first version" > time/newfile.txt 
```

You say, _"Repeat step 2...step 6"_. It is not immediately obvious which steps you are referring to.

Typos under https://github.com/NataliaLKB/learn-git-basics#when-should-you-commit: 
_"The first, is that a you..."
*"...depending on the extend of..."
*"...what tasks where completed..."_

This is just such a marvellous piece of work. I am very happy with where we are setting the bar for future tutorials.

**Comment by NataliaLKB** [comment]
@sofer since this is still for beginners I thought it was more clear to create the file, open it, and edit it in different steps. However if it isn't more clear, then happy to change it (This isn't a beginners guide to the command line though)
