### ISSUE TITLE
General form | Use of **bold**, _italic_, [links]() & `code`

### ISSUE THREAD

**Issue by iteles** [NataliaLKB/learn-git-basics#14]
I would suggest using **bold**, _italic_ & `code` to highlight the most important information and bring interest to those long paragraphs. You want people to be able to skim them and still come away with all the useful information.

**Comment by iteles** [comment]
A possible (very initial) example:
The [Git for Collaboration](https://github.com/NataliaLKB/learn-git-basics#git-for-collaboration) section is aimed at the _second week_ students of the course. Even though most of the advice in this tutorial will take a while to digest, **practise is essential**. A good goal is to understand all these concepts, and **implement most of these tips in your collaborative projects** before finishing your time as a student at Founders & Coders.

**Comment by NataliaLKB** [comment]
@iteles though I agree partially, I personally find it distracting to have too much **bold** or  _italic_ words . It makes it difficult for me to skim through it, rather than easier. 

I may be a minority here, but that is why I chose not to do more of it.

**Comment by iteles** [comment]
@NataliaLKB That's fair. May be a debate that's worth having with the wider group so we can create a tutorial style guide :wink:
