### ISSUE TITLE
Terminology | Definitions

### ISSUE THREAD

**Issue by iteles** [NataliaLKB/learn-git-basics#15]
**Commit**  
You need to point out the difference between the _verb_ **to** commit and the _noun_ **a** commit. You have the verb in this section mostly, but you use the noun in the first sentence of ‘Why Version Control'.

I think adding that all commits are 'saved **and accessible**' at any time would clarify a little as well :blush: 

**Branching**
This isn't really a definition of branching - it jumps straight into using the branching terminology without actually giving a sentence or diagram on what it actually is.

**Fork**
Used in the first section of the tutorial but not defined.

_Diagrams are particularly useful for branching and forking, but would be fantastic throughout the tutorial as they make git concepts much easier to understand_.

**Comment by NataliaLKB** [comment]
Closing as I think a lot of this i covered in the pre reqs now.
