### ISSUE TITLE
Show an overview of what a GitHub Repo looks like before diving in?

### ISSUE THREAD

**Issue by nelsonic** [NataliaLKB/learn-git-basics#16]
https://github.com/NataliaLKB/learn-git-basics/blame/1116839e12c4165cb1b232747b466189e216ec7c/README.md#L103 
You mention '_On the main page of the repo_" but do not show a full overview.
would highly recommend including a sample repo full page to give people context of where the UI elements are.

**Comment by NataliaLKB** [comment]
Interesting, but I think thats out of scope for this tutorial
