### ISSUE TITLE
Prerequisites << Add link to create GitHub account at start of tutorial.

### ISSUE THREAD

**Issue by nelsonic** [NataliaLKB/learn-git-basics#18]
I would add a **Prerequisites** section to clearly explain what people need to know **_before**_ starting this tutorial. At the top of this list would be:
- Register on GitHub (if you have not already): https://github.com/join
- Understand code basics (e.g. HTML & CSS) ... this will help them see the benefits of version control a lot better. 
- Any others pre-reqs...?

**Comment by NataliaLKB** [comment]
Closing as Founders & Coders students already have that as a pre-req
