### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by nelsonic** [NataliaLKB/learn-git-basics#19]
In the **Code Base History** section, **differences** should be **_different**_ 

> https://github.com/NataliaLKB/learn-git-basics/blame/1116839e12c4165cb1b232747b466189e216ec7c/README.md#L76

Not strictly a "typo" but, https://github.com/NataliaLKB/learn-git-basics/blame/1116839e12c4165cb1b232747b466189e216ec7c/README.md#L102
Section title **Getting Starting** _could_ be Getting **_Started**_ (sounds more familiar).

> Will add to this...

**Comment by iteles** [comment]
@NataliaLKB I picked up on a few more but they're an odd thing to write into issues so what I'll do is add them as inline comments to a pull request once you've made some more updates to the readme. That might be easier than explaining the context for each one!

**Comment by iteles** [comment]
Ah, one thing to add here before I forget, the Github Collaboration link in the main table of contents is broken (should be #git- **-for-** collaboration)

**Comment by NataliaLKB** [comment]
@nelsonic @iteles thanks for this. Typos should be fixed now. 

One thing, @iteles I believe that the git collaboration link is working. Please check and let me know if this is still a problem.

I will close this issue, but we can re-open if anything else!
