### ISSUE TITLE
Minor additions

### ISSUE THREAD

**Issue by rorysedgwick** [NataliaLKB/learn-git-basics#2]
Possible inclusions based on what I found confusing when learning version control:

On the line about adding comments to commits: emphasise the necessity of a message otherwise you end up in VIM, which is pretty confusing and difficult to exit if you haven't seen it before.

Explain that when using push or pull, 'origin' refers to the location(usually/always? the remote repo) and 'master' is referring to the branch there. For a while I did not understand the difference between them.

That merging locally and merging on GitHub is the same step twice, so not mandatory but gives extra control of remote repo.

When pushing to the remote repo the new branch has to have the exact same name as the local branch as you are pushing a copy of it.

A couple of times referring to a pull request as a PR may be confusing for those not familiar with the overall process.

These feel like very nitpicky points for what will be an amazing learning resource for newcomers to Git, but are things I was slightly confused by to begin with so may be worth including.

**Comment by NataliaLKB** [comment]
:+1: great feedback. Exactly what this tutorial needs. I will put in some though and let you know when I have updated the tutorial and you can let me know if it is better :smile:

**Comment by NataliaLKB** [comment]
@rorysedgwick please check my PR #3 . Let me know if I have clarified things a bit better! Thanks.

**Comment by rorysedgwick** [comment]
Yep that seems clearer and covers all the bits I thought were missing
