### ISSUE TITLE
Use Brew to install Git? What is brew?

### ISSUE THREAD

**Issue by nelsonic** [NataliaLKB/learn-git-basics#21]
On line https://github.com/NataliaLKB/learn-git-basics/blame/1116839e12c4165cb1b232747b466189e216ec7c/README.md#L98 you are recommending people install Git CLI tools using [Home**brew**](http://brew.sh/). 

While this is often recommended as the "_easy_" way of installing/upgrading the version of Git on Mac, e.g: http://apple.stackexchange.com/questions/93002/how-to-properly-update-git-on-mac 

But if you want the _latest_ version (brew is _usually_ behind by one release) its easy enough to download it directly: http://git-scm.com/download/mac see: http://superuser.com/questions/666086/issues-installing-git-under-mac-os-x-10-9-mavericks

If you are keen on keeping in the **brew** suggestion, maybe hyperlink it to a brew tutorial: 
http://computers.tutsplus.com/tutorials/homebrew-demystified-os-xs-ultimate-package-manager--mac-44884

**Comment by NataliaLKB** [comment]
Haha I never considered a tutorial for brew!

**Comment by NataliaLKB** [comment]
Yes I am keen for keeping the suggestion. As a beginner it is super useful to have a tool to help you manage things like git

**Comment by NataliaLKB** [comment]
I definitely will add the link to the tutorial. Thanks!

**Comment by NataliaLKB** [comment]
@nelsonic thanks again!
