### ISSUE TITLE
Tutorial Structure?

### ISSUE THREAD

**Issue by nelsonic** [NataliaLKB/learn-git-basics#22]
Would it be helpful to enumerate the sections for structure (and have a catchy blog post title?) ?
e.g:
#11 Things You Need to Know Git
1. **What** is Git and **Why** do I need it?
2. **init** - initialise a folder on your computer as a git repository (would also need to show creating the repo on GitHub)
3. **clone** - make a copy of an existing project (e.g. from GitHub)
4. **add** - add specific files you have changed or all files at once.
5. **commit** - save your work as a version.
6. **pull** - retrieve the changes others have made (updates your local copy of the project)
7. **push** - sends the changes you have made to files/folders to the remote repository
8. **Checkout** / **Branching** - create a new feature
9. **merge** - Apply the changes you have made to the main repository
10. **_Resolve**_ **Merge Conflicts** - Inevitably when working in a team...
11. **Revert** - if you want to go back to a previous version of your code. (the power of version control... History.)

Then it makes it easier for others to extend your tutorial with other topics/sections they find useful.
e.g:
1. **Forking** - useful when you want to contribute to someone else's project
2. **Issues** - creating an issue is the easiest way to get started contributing to projects.
3. **Commenting** on commits using line references
4. **Pull Requests** - Collaboration
5. **History/Blame** (see who made what change in the GitHub UI)
6. **Star**ring & **Watch**ing
7. **Forcing** (should you ever force push a commit?)
8. **Deleting** ("Pruning") branches you no longer need.
9. **Other** Git hosting **providers** (its not _just_ GitHub...) e.g: BitBucket allows you to have unlimited Private repos for free (provided you have a small team): https://bitbucket.org/plans

This way the contributors to your repository/tutorial could discuss and vote on the ordering of the sections and easily propose new ones or expand on existing... 

If it got to the point that you had an _exhaustive_ list of **GitFu _The_ 67 things you need to know Git** your post will move from being a "beginner" post to the Number 1 linked to & starred tutorial on the internet (hacker news, reddit, etc.)

Again, just a _suggestion_... :+1:

**Comment by NataliaLKB** [comment]
Thanks for the suggestions! Closing as I think this is working right now for Founders & Coders students with https://github.com/NataliaLKB/learn-git-basics/pull/77

**Comment by nelsonic** [comment]
❤️

**Comment by jsms90** [comment]
I'm afraid, after all that https://github.com/foundersandcoders/master-reference/issues/286

Just pointing it out in case you wanted to revert back from my PR, since it assumes FAC prereqs?
