### ISSUE TITLE
section on .gitignore ?

### ISSUE THREAD

**Issue by nelsonic** [NataliaLKB/learn-git-basics#41]
@jackpandas just noted that his team are having merge conflicts because of  .**DS_Store** files...
Which made me wonder if your Git tutorial has a section on .**gitignore** ...
- http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository
- https://github.com/github/gitignore/blob/master/Node.gitignore

**Comment by NataliaLKB** [comment]
Completing agree need to have a section on **.gitignore**!

https://github.com/NataliaLKB/learn-git-basics/issues/6 

On my todo list.

**Comment by nelsonic** [comment]
Maybe @lukars can submit a PR with the insight he learned today...? 😉

**Comment by nelsonic** [comment]
@NataliaLKB / @lukars let us know if you have time to add this. if not, I can submit a PR with the section.
(I really want to reference this from a tutorial I am writing right now...) :wink:

**Comment by NataliaLKB** [comment]
@nelsonic I don't have time to add to this right now. If either @lukars or you would submit a PR that would be great!! :+1:

**Comment by nelsonic** [comment]
duplicate of: https://github.com/NataliaLKB/learn-git-basics/issues/6 (_closing_)
