### ISSUE TITLE
Git Flow Chart

### ISSUE THREAD

**Issue by jrans** [NataliaLKB/learn-git-basics#43]
An alternate to downloading the source tree app (by the same makers).

http://beta.gitflowchart.com/

Looks like they do the same thing! Don't know which is better!

Think I've just about got my head around git! Thanks for the tutorial!

Still more material to get through but particularly like pcottles and also Try Git was a nice starting place too. https://try.github.io/levels/1/challenges/1

**Comment by NataliaLKB** [comment]
Hey @jrans closing this, but feel free to make a PR anytime!
