### ISSUE TITLE
"Unhappy Path"

### ISSUE THREAD

**Issue by rjmk** [NataliaLKB/learn-git-basics#44]
Thank you for this! It was really helpful this week.

My main issues came when I had diverged from the route of the tutorial and not realised. A mistake I kept making was:
1. Make some changes to some files.
2. Stage the files
3. Realise I was on the main branch
4. Try to checkout to a new branch
5. Oh no!

I realised I could unstage and then create the new branch and commit. Perhaps an FAQ/Troubleshooting section would be useful?

**Comment by NataliaLKB** [comment]
Hey @rjmk feel free to make a PR, but I don't have time right now. Closing but anyone can reopen!
