### ISSUE TITLE
Numbering the steps in the section "Timeline"

### ISSUE THREAD

**Issue by Jbarget** [NataliaLKB/learn-git-basics#58]
Hey Natalia,

Thanks for making this tutorial!
Just a small observation, in the Timeline section under Git for Collaboration, you refer to each step by their number, eg. "step 2". However the steps themselves aren't numbered. I would find it easier to follow if they we're numbered so i could connect the "step #" with is code equivalent.

It might also be helpful when learning as a beginner to have the steps numbered in all of the sections so that you know that you're on step 1 rather than thinking you're on step "mkdir" which is foreign terminology at this point. Although on the other hand it might be beneficial to be chucked in and having to start using that terminology internally from the start of the learning.

**Comment by NataliaLKB** [comment]
@Jbarget makes perfect sense! Have time to do a quick PR this week?

**Comment by Jbarget** [comment]
@NataliaLKB Heya! only just saw this. I'll look to do it over the weekend at some point :)

**Comment by NataliaLKB** [comment]
@Jbarget thanks. :star:
