### ISSUE TITLE
Which directory to Fork / clone your git repo? 

### ISSUE THREAD

**Issue by tormod17** [NataliaLKB/learn-git-basics#59]
Something that had me a wee bit doubtful about the fork then clone instructions were as to where exactly to do this. Just a one liner about adding a 'github directory' or 'Projects_Folder'. 

Side note pink box on git status chops off the part which also displays which branch you're on.

**Comment by NataliaLKB** [comment]
I never thought about mentioning this, as everyone I know has a different place where they like things. But it is a good point.

Have time to do a PR?

**Comment by NataliaLKB** [comment]
Closing, but feel free to reopen!
